### ISSUE TITLE
AdvHD D3D9 Wrapper Bug

### ISSUE THREAD

**Issue by canyeweishang** [marcussacana/StringReloads#11]
The test game is Golden Marriage -Jewel Days-
I tried using the auto-install feature of x86 SRLwrapper, but it just crashed on black screen at startup
.
The game uses the adv engine and the is original
I move both, SRL.ini and SRLWrapper.dll to the game folder (where .exe is), then i rename SRLWrapper.dll to d3d9.dll, open the SRL.ini and set the AutoInstall=true

**Comment by marcussacana** [comment]
You added any .lst to the SRL? If the game just closed without say anything should be this the problem.
The SRL only works if there are at least one Strings.lst file in the StringReloads directory.

**Comment by canyeweishang** [comment]
How do I generate a .lst？ I tried to use LST Generator but an error is displayed when I open it.

**Comment by marcussacana** [comment]
For testing only, you can just create an empty .lst file, that's enought to make the SRL don't close the game if that is the error.

**Comment by canyeweishang** [comment]
I deleted Cache.srl and created a new empty .lst. But the game still crashes after the black screen

**Comment by canyeweishang** [comment]
[SRL.log](https://github.com/marcussacana/StringReloads/files/8514215/SRL.log)

**Comment by canyeweishang** [comment]
I have sent it

**Comment by marcussacana** [comment]
![image](https://user-images.githubusercontent.com/10576957/164059145-f8764923-520c-4a30-aee9-bf5216bb2c07.png)
Not contain a link

**Comment by marcussacana** [comment]
![image](https://user-images.githubusercontent.com/10576957/164059238-1efa0824-d2fa-4e2c-81cf-b3186df7ff6a.png)

don't contain a link

**Comment by canyeweishang** [comment]
Is there a link this time?

**Comment by marcussacana** [comment]
have but I can't download, the file isn't public

**Comment by canyeweishang** [comment]
Maybe you can copy it into a browser to open

**Comment by canyeweishang** [comment]
Can the link open now?

**Comment by marcussacana** [comment]
I give up, the download take hours and got a Error, now the link isn't acessible again,
if possible reupload in google drive or something like that

**Comment by canyeweishang** [comment]
A Google drive download link for the game has been sent

**Comment by marcussacana** [comment]
should be fixed with [2a85357](https://github.com/marcussacana/StringReloads/commit/2a85357f5259d52307f1ac05085972cb9e815eef)
Test it.

**Comment by marcussacana** [comment]
You just reported me a bug that has there for more than 3 years and no one tried to report me, thx.

**Comment by canyeweishang** [comment]
Thank you very much.The game now opens normally, but .lst I still can't generate properly. I tried to use LST Generato, but it will show an error
![image](https://user-images.githubusercontent.com/103740149/164237986-24249486-54bc-4a6e-8f2f-df341d3b31b4.png)

**Comment by marcussacana** [comment]
that's is the PMan very outdated, download from this github the PMan.exe https://github.com/marcussacana/SacanaWrapper
